"use client";

import { useEffect, useState, useRef } from "react";
import { CategorySidebar } from "./CategorySidebar";
import { CategoryToolList } from "./CategoryToolList";
import { CategoryHeader } from "./CategoryHeader";
import { CategorySkeleton } from "./CategorySkeleton";
import { HeroSection } from "./HeroSection";
import { FeaturedSection } from "./FeaturedSection";
import { useRouter } from "next/navigation";

interface CategoryPageProps {
  group: string;
}

interface CategorySection {
  id: string;
  name: string;
  tools: Array<{
    id: number;
    name: string;
    count: number;
  }>;
}

// 模拟特色工具数据
const featuredTools = [
  {
    id: 1,
    name: "iFable",
    description:
      "Your Personal Anime Universe Generated by AI: Where Every Character Has a Story",
    imageUrl: "/images/tools/ifable.png",
    category: "--",
    views: 4,
    url: "/tools/ifable",
  },
  {
    id: 2,
    name: "Rubli AI",
    description:
      "Rubli AI native fandom character UGC platform. Create your character, feed stories, join community.",
    imageUrl: "/images/tools/rubli-ai.png",
    category: "AI Character",
    subcategory: "Novel",
    views: 45,
    popularity: "475.0K",
    growthRate: "33.83%",
    url: "/tools/rubli-ai",
  },
  {
    id: 3,
    name: "Powered_By",
    description:
      "Custom AI agents tailored for small and medium-sized businesses.",
    imageUrl: "/images/tools/powered-by.png",
    category: "AI Voice Assistants",
    views: 6,
    url: "/tools/powered-by",
  },
  {
    id: 4,
    name: "Easycart",
    description: "Create a high converting one-click checkout in minutes",
    imageUrl: "/images/tools/easycart.png",
    category: "No Code/Low Code",
    views: 0,
    popularity: "133.8K",
    growthRate: "81.37%",
    url: "/tools/easycart",
  },
];

export function CategoryPage({ group }: CategoryPageProps) {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(true);
  const [activeSection, setActiveSection] = useState(group);
  console.log("Active section:", activeSection, "URL group:", group);
  const [categorySections, setCategorySections] = useState<CategorySection[]>(
    []
  );
  const sectionRefs = useRef<Record<string, HTMLDivElement | null>>({});
  const initialScrollDone = useRef(false);
  const contentRef = useRef<HTMLDivElement>(null);

  // 确保activeSection始终与URL参数同步
  useEffect(() => {
    if (group !== activeSection) {
      setActiveSection(group);
      initialScrollDone.current = false; // 重置滚动状态，允许重新滚动
    }
  }, [group, activeSection]);

  useEffect(() => {
    const fetchCategoryData = async () => {
      setIsLoading(true);
      try {
        // 模拟获取所有分类数据
        const sections = generateCategorySections();
        // 根据当前分类组调整顺序，将当前分类组放在最前面
        const sortedSections = sortSectionsByGroup(sections, group);
        setCategorySections(sortedSections);
      } catch (error) {
        console.error("Error fetching category data:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchCategoryData();
  }, [group]);

  // 初始化滚动到指定分类
  useEffect(() => {
    if (
      !isLoading &&
      !initialScrollDone.current &&
      categorySections.length > 0
    ) {
      // 等待DOM更新完成后再滚动
      setTimeout(() => {
        const element = sectionRefs.current[group];
        if (element) {
          // 使用更平滑的滚动
          const headerOffset = 80; // 调整这个值来控制滚动的偏移量
          const elementPosition = element.getBoundingClientRect().top;
          const offsetPosition =
            elementPosition + window.pageYOffset - headerOffset;

          window.scrollTo({
            top: offsetPosition,
            behavior: "smooth",
          });

          initialScrollDone.current = true;
        }
      }, 300); // 增加延迟，确保DOM已完全渲染
    }
  }, [isLoading, group, categorySections]);

  // 监听滚动事件，更新当前活动的分类
  useEffect(() => {
    const handleScroll = () => {
      if (!contentRef.current || categorySections.length === 0) return;

      const scrollPosition = window.scrollY + 100; // 添加一些偏移量
      const contentTop = contentRef.current.offsetTop;

      // 找到当前在视图中的分类
      let foundActive = false;

      // 按照DOM顺序检查元素，确保选择最上面的可见元素
      for (const section of categorySections) {
        const element = sectionRefs.current[section.id];
        if (!element) continue;

        const { offsetTop, offsetHeight } = element;

        if (
          scrollPosition >= offsetTop - 50 &&
          scrollPosition < offsetTop + offsetHeight - 50
        ) {
          if (activeSection !== section.id) {
            setActiveSection(section.id);
            // 不更新URL，避免循环
          }
          foundActive = true;
          break;
        }
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, [categorySections, activeSection]);

  // 处理导航点击
  const handleNavClick = (sectionId: string) => {
    console.log("Navigating to section:", sectionId);

    if (sectionId === activeSection) return; // 避免重复点击

    setActiveSection(sectionId);

    // 更新URL参数
    router.push(`/category?group=${sectionId}`, { scroll: false });

    const element = sectionRefs.current[sectionId];
    if (element) {
      const headerOffset = 80; // 调整这个值来控制滚动的偏移量
      const elementPosition = element.getBoundingClientRect().top;
      const offsetPosition =
        elementPosition + window.pageYOffset - headerOffset;

      window.scrollTo({
        top: offsetPosition,
        behavior: "smooth",
      });
    }
  };

  if (isLoading) {
    return <CategorySkeleton />;
  }

  return (
    <div className="container mx-auto px-4 py-8">
      {/* 添加Hero部分 */}
      <HeroSection categoryCount={233} />

      <div className="flex flex-col md:flex-row gap-8">
        <div className="w-full md:w-64 shrink-0">
          <div className="sticky top-4">
            <CategorySidebar
              activeCategory={activeSection}
              onCategoryClick={handleNavClick}
              categories={categorySections.map((section) => ({
                id: section.id,
                name: section.name,
              }))}
            />
          </div>
        </div>
        <div className="flex-1" ref={contentRef}>
          {/* 添加Featured部分 */}
          <FeaturedSection tools={featuredTools} />

          {categorySections.map((section) => (
            <div
              key={section.id}
              ref={(el: HTMLDivElement | null) => {
                sectionRefs.current[section.id] = el;
                return undefined;
              }}
              id={`section-${section.id}`}
              className="mb-8 pt-4" // 减小底部间距，添加顶部内边距用于滚动定位
            >
              <h2 className="text-2xl font-bold mb-4">{section.name}</h2>
              <CategoryToolList tools={section.tools} />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// 根据当前分类组排序分类部分
function sortSectionsByGroup(
  sections: CategorySection[],
  currentGroup: string
): CategorySection[] {
  return [...sections].sort((a, b) => {
    if (a.id === currentGroup) return -1;
    if (b.id === currentGroup) return 1;
    return 0;
  });
}

// 生成所有分类数据
function generateCategorySections(): CategorySection[] {
  const categories = [
    { id: "text-writing", name: "Text&Writing" },
    { id: "image", name: "Image" },
    { id: "video", name: "Video" },
    { id: "code-it", name: "Code&IT" },
    { id: "voice", name: "Voice" },
    { id: "business", name: "Business" },
    { id: "marketing", name: "Marketing" },
    { id: "ai-detector", name: "AI Detector" },
    { id: "chatbot", name: "Chatbot" },
    { id: "design-art", name: "Design&Art" },
    { id: "life-assistant", name: "Life Assistant" },
    { id: "3d", name: "3D" },
    { id: "education", name: "Education" },
    { id: "prompt", name: "Prompt" },
    { id: "productivity", name: "Productivity" },
    { id: "other", name: "Other" },
  ];

  return categories.map((category) => ({
    id: category.id,
    name: category.name,
    tools: generateToolsForCategory(category.id),
  }));
}

// 模拟生成分类工具数据
function generateToolsForCategory(group: string) {
  if (group === "text-writing") {
    return [
      { id: 1, name: "AI Blog Writer", count: 522 },
      { id: 2, name: "Handwriting", count: 56 },
      { id: 3, name: "Essay Writer", count: 295 },
      { id: 4, name: "Report Writing", count: 280 },
      { id: 5, name: "AI Story Writing", count: 472 },
      { id: 6, name: "Paraphraser", count: 572 },
      { id: 7, name: "Pick-up Lines Generator", count: 44 },
      { id: 8, name: "Writing Assistants", count: 2341 },
      { id: 9, name: "AI Content Generator", count: 4064 },
      { id: 10, name: "Quotes Generator", count: 24 },
      { id: 11, name: "Translate", count: 587 },
      { id: 12, name: "Copywriting", count: 893 },
      { id: 13, name: "Letter Writer", count: 175 },
      { id: 14, name: "AI Rewriter", count: 671 },
      { id: 15, name: "AI Bio Generator", count: 147 },
      { id: 16, name: "AI Poem & Poetry Generator", count: 69 },
      { id: 17, name: "Transcription", count: 591 },
      { id: 18, name: "AI Creative Writing", count: 597 },
      { id: 19, name: "AI Email Writer", count: 796 },
      { id: 20, name: "AI Product Description Generator", count: 2158 },
    ];
  } else if (group === "image") {
    return [
      { id: 21, name: "Text to Image", count: 795 },
      { id: 22, name: "AI Photo & Image Generator", count: 1983 },
      { id: 23, name: "AI Illustration Generator", count: 483 },
      { id: 24, name: "AI Avatar Generator", count: 410 },
      { id: 25, name: "AI Background Generator", count: 345 },
      { id: 26, name: "AI Banner Generator", count: 271 },
    ];
  }

  // 为其他分类生成一些示例数据
  return Array.from({ length: 6 }, (_, i) => ({
    id: i + 100,
    name: `${getCategoryName(group)} Tool ${i + 1}`,
    count: Math.floor(Math.random() * 1000),
  }));
}

// 辅助函数，根据分类ID获取分类名称
function getCategoryName(group: string): string {
  const categoryMap: Record<string, string> = {
    "text-writing": "Text&Writing",
    image: "Image",
    video: "Video",
    "code-it": "Code&IT",
    voice: "Voice",
    business: "Business",
    marketing: "Marketing",
    "ai-detector": "AI Detector",
    chatbot: "Chatbot",
    "design-art": "Design&Art",
    "life-assistant": "Life Assistant",
    "3d": "3D",
    education: "Education",
    prompt: "Prompt",
    productivity: "Productivity",
    other: "Other",
  };

  return categoryMap[group] || group;
}
