name: 每周数据同步

on:
  schedule:
    # 每周六凌晨2点执行 (UTC时间需要调整为前一天18点)
    - cron: "0 18 * * 5" # 每周五18:00 UTC = 周六02:00 CST
  workflow_dispatch: # 允许手动触发

jobs:
  sync-data:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 安装依赖
        run: bun install

      - name: 执行数据同步
        run: bun run sync
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY }}

      - name: 同步完成通知
        if: always()
        run: |
          echo "==================================="
          echo "数据同步工作流已完成"
          echo "完成时间: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "==================================="
